### ISSUE TITLE
redirectToRoute triggers a 403 error

### ISSUE THREAD

**Issue by fbnlsr** [SkipTheDragon/inertia-bundle#10]
I've been battling this issue for days but I can't find a solution for the life of me.

When using `$this->redirectToRoute()` inside a controller, it triggers an unexpected 403 error making inertia pop up a modal stating "Something went wrong with Inertia!"

Example controller: 

```php
<?php

namespace App\Controller;

use Rompetomp\InertiaBundle\Architecture\InertiaInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class BaseController extends AbstractController
{

    public function __construct(private InertiaInterface $inertia)
    {}

    #[Route('/', name: 'app_home')]
    public function index(): Response
    {
        return $this->redirectToRoute('app_about');
    }

    #[Route('/about', name: 'app_about')]
    public function about(): Response
    {
        return $this->inertia->render('AboutView');
    }

}
```

The problem only arises when using `Link` components. When a user goes to `/` with their browser directly, the redirection is properly interpreted and the correct page is called.

I tried using the Security bundle, as well as with a barebone install, no luck.

I can't figure out if it's an Inertia issue or if the problem comes from the Symfony adapter.

**Comment by SkipTheDragon** [comment]
Hi, looks like you encountered the same problem as #8. You can disable CSRF for now in your inertia.yaml. 

```yaml
inertia:
  # The rest of your configuration here.....
  csrf:
    enabled: false
```

**Comment by fbnlsr** [comment]
@SkipTheDragon yup, that was it. I also confirm that updating the bundle to `1.1.2` fixed the issue without having to disable CSRF inside the config.

Thanks a lot for your work! <3
