### ISSUE TITLE
Different default root view (template) in recipe and docs

### ISSUE THREAD

**Issue by aleksblendwerk** [SkipTheDragon/inertia-bundle#14]
First of all, many thanks to you for picking up this abandoned project!

A minor inconvenience I found when I replaced the old package with yours: 

In the default configuration in https://github.com/symfony/recipes-contrib/blob/main/skipthedragon/inertia-bundle/1.0/config/packages/inertia.yaml#L9C1-L10C1, the root view (template) is set to `base.html.twig` while the docs at https://github.com/SkipTheDragon/inertia-bundle/blob/master/docs/configuration.md recommend to use `app.html.twig`, same as the predecessor `rompetomp/inertia-bundle` did.

**Comment by SkipTheDragon** [comment]
Hi,

I'll take a look over it. Hopefully this weekend.

**Comment by aleksblendwerk** [comment]
I'd say by Symfony defaults `base.html.twig` is actually the way to go, so I guess updating the docs would be sufficient.
