### ISSUE TITLE
"Rompetomp\InertiaBundle\Architecture\InertiaInterface" is not an existing service

### ISSUE THREAD

**Issue by iArcadia** [SkipTheDragon/inertia-bundle#7]
I tried to install the package but this exception is raised when using `InertiaTrait`:

```
Cannot autowire service "App\Controller\FrontController": argument "$inertiaService" of method "setInertiaService()" references interface "Rompetomp\InertiaBundle\Architecture\InertiaInterface" but no such service exists. Did you create a class that implements this interface?
```

And this exception is raised when autowiring:

```
The service "App\Controller\FrontController" has a dependency on a non-existent service "Rompetomp\InertiaBundle\Architecture\InertiaInterface".
```

**PHP version:** 8.2
**Symfony version:** Tried with 6.3 and 7.1

**Code snippet:**

```php
namespace App\Controller;

use Rompetomp\InertiaBundle\Architecture\InertiaInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Contracts\Service\Attribute\Required;

class FrontController extends AbstractController {
    // Or:
    // use InertiaTrait;

    #[Required]
    public InertiaInterface $inertia;

    #[Route('/', name: 'home')]
    public function index() {
        return $this->inertia->render('HomePage');
    }
}
```

**composer.json:**

```json
"skipthedragon/inertia-bundle": "^1.1"
```

I also tried to autowire `InertiaService` but it didn't work.

**Comment by SkipTheDragon** [comment]
Hi,

I'll have a look over the weekend.

**Comment by SkipTheDragon** [comment]
Hi, I can't seem to reproduce this error. I have tried to reproduce it in this project: https://github.com/SkipTheDragon/nft-marketplace/tree/admin-panel

Your controller: https://github.com/SkipTheDragon/nft-marketplace/blob/admin-panel/src/Controller/FrontController.php

P.s.: I have tested with symfony 7.0 and 7.1, did you try cleaning the cache or removing the vendor folder and reinstalling your dependencies?

**Comment by SkipTheDragon** [comment]
Also, could you provide me with a repository showcasing this problem? That would greatly help me in finding what's wrong.
